[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    # Default exclusions provided by ruff
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",

    # Project specific exclusions
    "migrations",
]
per-file-ignores = {"__init__.py" = ["F401"]}
target-version = "py310"


[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # flake8-bandit
    "S",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
     # flake8-comprehensions
    "C4",
    # flake8-print
    "T",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
