# Generated by Django 5.0.2 on 2025-08-19 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, unique=True
                    ),
                ),
                ("first_name", models.CharField(db_index=True, max_length=50)),
                ("last_name", models.CharField(db_index=True, max_length=50)),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("mobiux_employee", "Mobiux Employee"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("executive_leadership", "Executive / Leadership"),
                            ("business_consulting", "Business / Consulting"),
                            ("engineering_development", "Engineering / Development"),
                            ("design", "Design"),
                            ("quality_assurance", "Quality Assurance"),
                            ("hr_admin", "HR & Admin"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("managing_partner", "Managing Partner"),
                            ("head_of_engineering", "Head of Engineering"),
                            ("head_of_sales", "Head of Sales"),
                            (
                                "business_operations_manager",
                                "Business Operations Manager",
                            ),
                            (
                                "business_development_manager",
                                "Business Development Manager",
                            ),
                            ("business_consultant", "Business Consultant"),
                            ("business_analyst_intern", "Business Analyst Intern"),
                            ("ai_architect", "AI Architect"),
                            ("principal_engineer", "Principal Engineer"),
                            ("engineering_tech_lead", "Engineering Tech Lead"),
                            ("solutions_architect", "Solutions Architect"),
                            ("sr_software_engineer", "Sr Software Engineer"),
                            ("software_engineer", "Software Engineer"),
                            ("ai_engineer", "AI Engineer"),
                            ("software_developer_intern", "Software Developer Intern"),
                            ("design_lead", "Design Lead"),
                            ("senior_designer", "Senior Designer"),
                            ("designer", "Designer"),
                            ("sr_qa_engineer", "Sr QA Engineer"),
                            ("qa_engineer", "QA Engineer"),
                            ("qa_intern", "QA Intern"),
                            ("hr_admin_manager", "HR & Admin Manager"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("hire_date", models.DateField(db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="employees.employee",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["employee_id"],
                "indexes": [
                    models.Index(fields=["email"], name="employees_e_email_8f5bbc_idx"),
                    models.Index(
                        fields=["department", "is_active"],
                        name="employees_e_departm_c5cc9c_idx",
                    ),
                    models.Index(
                        fields=["role", "is_active"], name="employees_e_role_3e6dfe_idx"
                    ),
                    models.Index(
                        fields=["designation", "is_active"],
                        name="employees_e_designa_c97ae9_idx",
                    ),
                    models.Index(
                        fields=["manager", "is_active"],
                        name="employees_e_manager_4f2c90_idx",
                    ),
                    models.Index(
                        fields=["is_active", "hire_date"],
                        name="employees_e_is_acti_f30478_idx",
                    ),
                    models.Index(
                        fields=["employee_id", "is_active"],
                        name="employees_e_employe_6a28c0_idx",
                    ),
                    models.Index(
                        fields=["first_name", "last_name"],
                        name="employees_e_first_n_597cbd_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="employees_e_created_9cbbc2_idx"
                    ),
                ],
            },
        ),
    ]
