# Generated by Django 5.0.2 on 2025-08-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.CharField(blank=True, default="Mobiux", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="designation",
            field=models.CharField(
                choices=[
                    ("employee", "Employee"),
                    ("senior_employee", "Senior Employee"),
                    ("team_lead", "Team Lead"),
                    ("manager", "Manager"),
                    ("senior_manager", "Senior Manager"),
                    ("director", "Director"),
                ],
                default="employee",
                help_text="User's designation in the company",
                max_length=50,
            ),
        ),
    ]
