# Generated by Django 5.0.2 on 2025-08-22 05:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_type", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(24.0),
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("submitted", "Submitted")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("user_name", models.CharField(blank=True, max_length=201)),
                ("project_name", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheets",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="timesheets__user_id_c8ea5e_idx"
                    ),
                    models.Index(
                        fields=["project", "date"],
                        name="timesheets__project_20fe53_idx",
                    ),
                    models.Index(fields=["date"], name="timesheets__date_f1b81d_idx"),
                    models.Index(
                        fields=["user", "project", "date"],
                        name="timesheets__user_id_bf2ef5_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="timesheets__created_f5cc6d_idx"
                    ),
                    models.Index(
                        fields=["status"], name="timesheets__status_d1d005_idx"
                    ),
                ],
                "unique_together": {
                    ("user", "project", "date", "activity_type", "status")
                },
            },
        ),
    ]
