# Generated by Django 5.0.2 on 2025-08-25 12:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("timesheets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="timesheet",
            unique_together={("user", "project", "date", "activity_type")},
        ),
    ]
